Default: &defaults
  database: ParanoiaTracker.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ParanoiaTracker_test.sqlite3
  <<: *defaults

Staging:
  database: ParanoiaTracker_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ParanoiaTracker_production.sqlite3
  poolsize: 100
  <<: *defaults
